scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['dinos-be-test.herokuapp.com']
        labels:
          application: 'Dino Dev version'
      - targets: [ 'itdinos.herokuapp.com' ]
        labels:
          application: 'Dino Prod version'