server:
  port: ${DINO_CONTAINER_PORT:10050}
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  application:
    name: dinosaurs-service
  profiles:
    active: emailEnable
  jackson:
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dinodb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false
  mail:
    host: smtp.yandex.com
    port: 465
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtps
    test-connection: true


role:
  hierarchy: |
    ROLE_ADMIN > ROLE_MODERATOR
    ROLE_MODERATOR > ROLE_REGULAR

jwt:
  ttl: 86400
  secretKey: k+r/JkFxq9lO+iqf3zY+/Wgr2bu31LoiUwIb26amlB9/VAsFEyK7vi7ubzP1RJQn


notification:
  email:
    confirmUrl: https://bootcamp-team2.herokuapp.com/confirm


management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: when_authorized
    loggers:
      enabled: true


services:
  course:
    default-internal-rating: 100
    default-is-indefinite: true
    default-is-archived: false
    default-page-size: 9
  profession:
    default-page-size: 9
  provider:
    default-page-size: 9
