INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (13, 'https://geekhacker.ru/wp-content/uploads/2020/08/jandeks-praktikum-logo-2.png', 'Освойте востребованную IT-профессию', 'Яндекс Практикум', null, 'https://practicum.yandex.ru/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (83, 'https://www.sostav.ru/images/news/2020/05/21/exkn8ppz.png', 'Образовательная платформа
Учим профессиям и навыкам', 'Нетология', null, 'https://netology.ru/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (84, 'https://loftschool.com/_nuxt/1c49286792facb9d3e02511cb4a94ceb.svg', 'Школа онлайн обучения IT профессиям', 'Loftschool', null, 'https://loftschool.com/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (85, 'https://static.tildacdn.com/tild3061-3362-4663-b666-663433356636/d1b00f4f237b5c563537.svg', 'Онлайн-школа дизайна', 'Contented', null, 'https://contented.ru/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (86, 'https://onlineitea.com/wp-content/themes/itea/images/logo/logo.svg', 'Быстрый старт твоей IT-карьеры', 'Itea online', null, 'https://onlineitea.com/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (87, 'https://static.tildacdn.com/tild3934-3832-4738-a665-646331376534/SF_MRG_-_black.svg', 'SkillFactory — ваш прямой путь в IT-профессии', 'SkillFactory', null, 'https://skillfactory.ru/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (88, 'https://cdn.specialist.ru/Content/File/Site_rework/index-2/i/index-2/logo-desktop.png', 'Мировые стандарты обучения', 'Учебный центр при МГТУ имени Н. Э. Баумана', null, 'https://www.specialist.ru/');
INSERT INTO public.course_provider (id, cover_url, description, name, short_description, url) VALUES (89, 'https://248006.selcdn.ru/MainSite/skillbox.svg', 'Образовательная платформа', 'Skillbox', null, 'https://skillbox.ru/');
