server:
  port: ${DINO_CONTAINER_PORT:10050}
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  application:
    name: dinosaurs-service
  jackson:
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dinodb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    enabled: false

role:
  hierarchy: |
    ROLE_ADMIN > ROLE_MODERATOR
    ROLE_MODERATOR > ROLE_REGULAR

jwt:
  ttl: 86400
  secretKey: k+r/JkFxq9lO+iqf3zY+/Wgr2bu31LoiUwIb26amlB9/VAsFEyK7vi7ubzP1RJQn

endpoints:
  health:
    id: healthcheck
    enabled: true
