name: CI with gradle

on:
  pull_request:
    types: [ opened, review_requested ]
    branches: [ dev ]

jobs:
  runs-on: ubuntu-22.04
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run verification task via Gradle
      run: ./gradlew check
